### Подключение к базе и основные таблицы

In [1]:
import pandas as pd

### Данные по пользователям

user_info = pd.read_sql(
    """SELECT * FROM public.user_data""",
    
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

user_info.head()

   user_id  gender  age country               city  exp_group       os source
0      200       1   34  Russia          Degtyarsk          3  Android    ads
1      201       0   37  Russia             Abakan          0  Android    ads
2      202       1   17  Russia           Smolensk          4  Android    ads
3      203       0   18  Russia             Moscow          1      iOS    ads
4      204       0   36  Russia  Anzhero-Sudzhensk          3  Android    ads

In [2]:
### Посты и топики

posts_info = pd.read_sql(
    """SELECT * FROM public.post_text_df""",
    
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

posts_info.head()

   post_id                                               text     topic
0        1  UK economy facing major risks\n\nThe UK manufa...  business
1        2  Aids and climate top Davos agenda\n\nClimate c...  business
2        3  Asian quake hits European shares\n\nShares in ...  business
3        4  India power shares jump on debut\n\nShares in ...  business
4        5  Lacroix label bought by US firm\n\nLuxury good...  business

In [3]:
### Почти 77 миллионов записей, многовато!
### Не в каждую оперативу влезет столько данных
### Для обучения моделей

count_feed_data = pd.read_sql(
    """SELECT count(*) FROM public.feed_data""",
    
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

count_feed_data.head()

      count
0  76892800

In [4]:
### Попробуем забрать, скажем, 10 миллионов

feed_data = pd.read_sql(
    """SELECT * FROM public.feed_data LIMIT 10000000""",
    
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

feed_data.head()

            timestamp  user_id  post_id action  target
0 2021-11-09 23:05:30    71774     1910   view       0
1 2021-11-09 23:07:47    71774     5971   view       0
2 2021-11-09 23:09:38    71774      679   view       0
3 2021-11-09 23:12:02    71774     3511   view       0
4 2021-11-09 23:12:20    71774     3320   view       0

### Работа с данными и фичи для контентной модели

In [5]:
### Как устроена колонка target?

feed_data[feed_data.action!='view']

                  timestamp  user_id  post_id action  target
7       2021-11-19 19:35:37    71774     5336   like       0
12      2021-11-19 19:40:40    71774     1813   like       0
16      2021-11-19 19:45:55    71774     1905   like       0
23      2021-11-19 19:57:49    71774      180   like       0
28      2021-11-19 20:03:25    71774     4536   like       0
...                     ...      ...      ...    ...     ...
9999940 2021-11-17 11:52:04    34726     1611   like       0
9999948 2021-11-17 12:05:21    34726     6485   like       0
9999969 2021-12-02 09:17:25    34726     1233   like       0
9999972 2021-12-02 09:20:59    34726     1277   like       0
9999990 2021-12-14 18:48:32    34726     6229   like       0

[1067385 rows x 5 columns]

In [6]:
### Почистим данные от action != view

feed_data = feed_data[feed_data.action == 'view']

feed_data.head()

            timestamp  user_id  post_id action  target
0 2021-11-09 23:05:30    71774     1910   view       0
1 2021-11-09 23:07:47    71774     5971   view       0
2 2021-11-09 23:09:38    71774      679   view       0
3 2021-11-09 23:12:02    71774     3511   view       0
4 2021-11-09 23:12:20    71774     3320   view       0

Напомним, как устроен контентный подход! 

Научимся по выбранной дате timestamp 

И для любой пары (user_id, post_id)

Предсказывать, случится лайк или нет

Хорошо бы иметь модель, которая умеет предсказывать вероятности

In [7]:
### Необходимо по user_id выделять 
### Фиксированный набор признаков
### В целом, подойдет оригинальный датасет

user_info

,user_id,gender,age,country,city,exp_group,os,source
0,200,1,34,Russia,Degtyarsk,3,Android,ads
1,201,0,37,Russia,Abakan,0,Android,ads
2,202,1,17,Russia,Smolensk,4,Android,ads
3,203,0,18,Russia,Moscow,1,iOS,ads
4,204,0,36,Russia,Anzhero-Sudzhensk,3,Android,ads
...,...,...,...,...,...,...,...,...
163200,168548,0,36,Russia,Kaliningrad,4,Android,organic
163201,168549,0,18,Russia,Tula,2,Android,organic
163202,168550,1,41,Russia,Yekaterinburg,4,Android,organic
163203,168551,0,38,Russia,Moscow,3,iOS,organic
163204,168552,1,16,Russia,Ivanteyevka,4,Android,organic

In [8]:
### C post_id куда интереснее!
### Придумаем какой-нибудь эмбеддинг 
### Для текстов

posts_info

      post_id                                               text     topic
0           1  UK economy facing major risks\n\nThe UK manufa...  business
1           2  Aids and climate top Davos agenda\n\nClimate c...  business
2           3  Asian quake hits European shares\n\nShares in ...  business
3           4  India power shares jump on debut\n\nShares in ...  business
4           5  Lacroix label bought by US firm\n\nLuxury good...  business
...       ...                                                ...       ...
7018     7315  OK, I would not normally watch a Farrelly brot...     movie
7019     7316  I give this movie 2 stars purely because of it...     movie
7020     7317  I cant believe this film was allowed to be mad...     movie
7021     7318  The version I saw of this film was the Blockbu...     movie
7022     7319  Piece of subtle art. Maybe a masterpiece. Doub...     movie

[7023 rows x 3 columns]

In [9]:
### Сделаем эмбеддинги постов с помощью моделей из 10 занятия

from transformers import AutoTokenizer
from transformers import BertModel  # https://huggingface.co/docs/transformers/model_doc/bert#transformers.BertModel
from transformers import RobertaModel  # https://huggingface.co/docs/transformers/model_doc/roberta#transformers.RobertaModel
from transformers import DistilBertModel  # https://huggingface.co/docs/transformers/model_doc/distilbert#transformers.DistilBertModel


def get_model(model_name):
    assert model_name in ['bert', 'roberta', 'distilbert']

    checkpoint_names = {
        'bert': 'bert-base-cased',  # https://huggingface.co/bert-base-cased
        'roberta': 'roberta-base',  # https://huggingface.co/roberta-base
        'distilbert': 'distilbert-base-cased'  # https://huggingface.co/distilbert-base-cased
    }

    model_classes = {
        'bert': BertModel,
        'roberta': RobertaModel,
        'distilbert': DistilBertModel
    }

    return AutoTokenizer.from_pretrained(checkpoint_names[model_name]), model_classes[model_name].from_pretrained(checkpoint_names[model_name])

In [10]:
tokenizer, model = get_model('roberta')

Some weights of the model checkpoint at roberta-base were not used when initializing RobertaModel: ['lm_head.layer_norm.bias', 'lm_head.decoder.weight', 'lm_head.layer_norm.weight', 'lm_head.bias', 'lm_head.dense.bias', 'lm_head.dense.weight']
- This IS expected if you are initializing RobertaModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).

In [11]:
### Сделаем датасет для постов

from torch.utils.data import Dataset
from torch.utils.data import DataLoader
from transformers import DataCollatorWithPadding


class PostDataset(Dataset):
    def __init__(self, texts, tokenizer):
        super().__init__()

        self.texts = tokenizer.batch_encode_plus(
            texts,
            add_special_tokens=True,
            return_token_type_ids=False,
            return_tensors='pt',
            truncation=True,
            padding=True
        )
        self.tokenizer = tokenizer

    def __getitem__(self, idx):
        return {'input_ids': self.texts['input_ids'][idx], 'attention_mask': self.texts['attention_mask'][idx]}

    def __len__(self):
        return len(self.texts['input_ids'])
    
    
dataset = PostDataset(posts_info['text'].values.tolist(), tokenizer)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

loader = DataLoader(dataset, batch_size=32, collate_fn=data_collator, pin_memory=True, shuffle=False)

b = next(iter(loader))

b

{'input_ids': tensor([[    0, 10494,   866,  ...,     1,     1,     1],
        [    0,   250,  7823,  ..., 18158,    26,     2],
        [    0, 36496, 15015,  ...,   231,   207,     2],
        ...,
        [    0,   565,  3765,  ...,     1,     1,     1],
        [    0,  1039, 28045,  ...,     1,     1,     1],
        [    0, 16389,  3631,  ...,     1,     1,     1]]), 'attention_mask': tensor([[1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0],
        [1, 1, 1,  ..., 0, 0, 0]])}

In [12]:
import torch
from tqdm import tqdm


@torch.inference_mode()
def get_embeddings_labels(model, loader):
    model.eval()
    
    total_embeddings = []
    
    for batch in tqdm(loader):
        batch = {key: batch[key].to(device) for key in ['attention_mask', 'input_ids']}

        embeddings = model(**batch)['last_hidden_state'][:, 0, :]

        total_embeddings.append(embeddings.cpu())

    return torch.cat(total_embeddings, dim=0)

In [13]:
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')

print(device)
print(torch.cuda.get_device_name())

model = model.to(device)

cuda:0
NVIDIA GeForce RTX 3090 Ti

In [14]:
embeddings = get_embeddings_labels(model, loader).numpy()

embeddings

100%|███████████████████████████████████████████████████| 220/220 [00:46<00:00,  4.71it/s]

array([[-0.03860577,  0.09835491,  0.02948288, ..., -0.08099221,
        -0.03544501, -0.0484763 ],
       [-0.00790149,  0.08904046,  0.04218249, ..., -0.07876965,
        -0.02434696,  0.01079471],
       [-0.06683082,  0.11239151,  0.03230242, ..., -0.12619439,
        -0.08494114, -0.0188031 ],
       ...,
       [-0.07701632,  0.051031  , -0.02830479, ..., -0.13749716,
        -0.05310539, -0.03514046],
       [-0.07431198,  0.08764899,  0.01007036, ..., -0.12020953,
        -0.00962659, -0.04021234],
       [-0.10920739,  0.09746816, -0.00142144, ..., -0.07132423,
         0.00438604,  0.04553597]], dtype=float32)

In [15]:
### Пытаемся кластеризовать тексты

from sklearn.decomposition import PCA

centered = embeddings - embeddings.mean()

pca = PCA(n_components=20)
pca_decomp = pca.fit_transform(centered)

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=15, random_state=0).fit(pca_decomp)

posts_info['TextCluster'] = kmeans.labels_

dists_columns = ['DistanceTo1thCluster',
                 'DistanceTo2thCluster',
                 'DistanceTo3thCluster',
                 'DistanceTo4thCluster',
                 'DistanceTo5thCluster',
                 'DistanceTo6thCluster',
                 'DistanceTo7thCluster',
                 'DistanceTo8thCluster',
                 'DistanceTo9thCluster',
                 'DistanceTo10thCluster',
                 'DistanceTo11thCluster',
                 'DistanceTo12thCluster',
                 'DistanceTo13thCluster',
                 'DistanceTo14thCluster',
                 'DistanceTo15thCluster']

dists_df = pd.DataFrame(
    data=kmeans.transform(pca_decomp),
    columns=dists_columns
)

dists_df.head()

,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster
0,0.678915,1.242555,0.925453,1.328624,1.035016,0.746756,1.047396,1.202399,1.058816,0.596554,0.467959,1.303139,0.779649,0.433943,1.151153
1,0.515767,1.086312,0.754733,1.208146,0.895864,0.575891,0.841598,1.078090,0.892187,0.450967,0.243006,1.176879,0.563903,0.364549,1.013353
2,0.553639,1.224138,0.759190,1.176707,0.880581,0.614857,1.001670,1.190090,0.842709,0.628899,0.521435,1.099705,0.623288,0.311780,0.961329
3,0.641349,1.051242,0.782907,1.173028,0.909068,0.704925,0.837270,1.043599,0.931570,0.706521,0.426988,1.166589,0.677383,0.349437,0.995106
4,0.528634,1.014662,0.661138,0.983044,0.709366,0.548295,0.810834,0.984994,0.748542,0.590418,0.442702,0.955124,0.436692,0.322252,0.830841

In [16]:
posts_info = pd.concat((posts_info, dists_df), axis=1)

posts_info.head()

,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster
0,1,UK economy facing major risks\n\nThe UK manufa...,business,13,0.678915,1.242555,0.925453,1.328624,1.035016,0.746756,1.047396,1.202399,1.058816,0.596554,0.467959,1.303139,0.779649,0.433943,1.151153
1,2,Aids and climate top Davos agenda\n\nClimate c...,business,10,0.515767,1.086312,0.754733,1.208146,0.895864,0.575891,0.841598,1.078090,0.892187,0.450967,0.243006,1.176879,0.563903,0.364549,1.013353
2,3,Asian quake hits European shares\n\nShares in ...,business,13,0.553639,1.224138,0.759190,1.176707,0.880581,0.614857,1.001670,1.190090,0.842709,0.628899,0.521435,1.099705,0.623288,0.311780,0.961329
3,4,India power shares jump on debut\n\nShares in ...,business,13,0.641349,1.051242,0.782907,1.173028,0.909068,0.704925,0.837270,1.043599,0.931570,0.706521,0.426988,1.166589,0.677383,0.349437,0.995106
4,5,Lacroix label bought by US firm\n\nLuxury good...,business,13,0.528634,1.014662,0.661138,0.983044,0.709366,0.548295,0.810834,0.984994,0.748542,0.590418,0.442702,0.955124,0.436692,0.322252,0.830841

In [17]:
### Воспроизведем датафрейм со всеми новыми фичами 

df = pd.merge(feed_data,
              posts_info,
              on='post_id',
              how='left')

df.head()

,timestamp,user_id,post_id,action,target,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,...,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster
0,2021-11-09 23:05:30,71774,1910,view,0,Wada will appeal against ruling\n\nThe World A...,sport,5,0.508622,1.236053,...,0.429453,1.056280,1.176828,0.775417,0.501607,0.618149,0.974422,0.567518,0.534671,0.909735
1,2021-11-09 23:07:47,71774,5971,view,0,I had heard news about this film from anime-le...,movie,4,0.801371,1.183909,...,0.789486,0.883998,1.158633,0.406410,0.924252,0.978681,0.402392,0.640163,0.888401,0.369618
2,2021-11-09 23:09:38,71774,679,view,0,Aviator creator in Oscars snub\n\nThe man who ...,entertainment,12,0.520916,1.218178,...,0.531203,0.920499,1.203230,0.604987,0.504516,0.591486,0.849487,0.238074,0.551598,0.770985
3,2021-11-09 23:12:02,71774,3511,view,0,Cabinet Secretary reviews the management of\r#...,covid,7,1.217534,0.356532,...,1.159151,0.872360,0.238470,1.286372,1.199381,1.048103,1.380035,1.121120,1.126135,1.266399
4,2021-11-09 23:12:20,71774,3320,view,0,Karnataka: The office of Department of Informa...,covid,7,1.195418,0.479484,...,1.119157,0.913641,0.249585,1.224746,1.171719,1.043684,1.305397,1.072225,1.098268,1.199113

In [18]:
df = pd.merge(df,
              user_info,
              on='user_id',
              how='left')

df.head()

,timestamp,user_id,post_id,action,target,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,...,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster,gender,age,country,city,exp_group,os,source
0,2021-11-09 23:05:30,71774,1910,view,0,Wada will appeal against ruling\n\nThe World A...,sport,5,0.508622,1.236053,...,0.567518,0.534671,0.909735,0,20,Russia,Ulyanovsk,4,iOS,ads
1,2021-11-09 23:07:47,71774,5971,view,0,I had heard news about this film from anime-le...,movie,4,0.801371,1.183909,...,0.640163,0.888401,0.369618,0,20,Russia,Ulyanovsk,4,iOS,ads
2,2021-11-09 23:09:38,71774,679,view,0,Aviator creator in Oscars snub\n\nThe man who ...,entertainment,12,0.520916,1.218178,...,0.238074,0.551598,0.770985,0,20,Russia,Ulyanovsk,4,iOS,ads
3,2021-11-09 23:12:02,71774,3511,view,0,Cabinet Secretary reviews the management of\r#...,covid,7,1.217534,0.356532,...,1.121120,1.126135,1.266399,0,20,Russia,Ulyanovsk,4,iOS,ads
4,2021-11-09 23:12:20,71774,3320,view,0,Karnataka: The office of Department of Informa...,covid,7,1.195418,0.479484,...,1.072225,1.098268,1.199113,0,20,Russia,Ulyanovsk,4,iOS,ads

In [19]:
### А еще научимся выделять признаки
### Из timestamp!
### Согласитесь, от времени просмотра может зависеть
### Склонность пользователей лайкать или игнорировать посты

df['hour'] = pd.to_datetime(df['timestamp']).apply(lambda x: x.hour)
df['month'] = pd.to_datetime(df['timestamp']).apply(lambda x: x.month)

df.head()

,timestamp,user_id,post_id,action,target,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,...,DistanceTo15thCluster,gender,age,country,city,exp_group,os,source,hour,month
0,2021-11-09 23:05:30,71774,1910,view,0,Wada will appeal against ruling\n\nThe World A...,sport,5,0.508622,1.236053,...,0.909735,0,20,Russia,Ulyanovsk,4,iOS,ads,23,11
1,2021-11-09 23:07:47,71774,5971,view,0,I had heard news about this film from anime-le...,movie,4,0.801371,1.183909,...,0.369618,0,20,Russia,Ulyanovsk,4,iOS,ads,23,11
2,2021-11-09 23:09:38,71774,679,view,0,Aviator creator in Oscars snub\n\nThe man who ...,entertainment,12,0.520916,1.218178,...,0.770985,0,20,Russia,Ulyanovsk,4,iOS,ads,23,11
3,2021-11-09 23:12:02,71774,3511,view,0,Cabinet Secretary reviews the management of\r#...,covid,7,1.217534,0.356532,...,1.266399,0,20,Russia,Ulyanovsk,4,iOS,ads,23,11
4,2021-11-09 23:12:20,71774,3320,view,0,Karnataka: The office of Department of Informa...,covid,7,1.195418,0.479484,...,1.199113,0,20,Russia,Ulyanovsk,4,iOS,ads,23,11

In [20]:
### Уберем все ненужные колонки

df = df.drop([
#    'timestamp',  ### timestamp пока оставим
    'action',
    'text',
],
    axis=1)

df = df.set_index(['user_id', 'post_id'])

df.head(50)

                          timestamp  target          topic  TextCluster  \
user_id post_id
71774   1910    2021-11-09 23:05:30       0          sport            5
        5971    2021-11-09 23:07:47       0          movie            4
        679     2021-11-09 23:09:38       0  entertainment           12
        3511    2021-11-09 23:12:02       0          covid            7
        3320    2021-11-09 23:12:20       0          covid            7
        1126    2021-11-19 19:31:09       0       politics            9
        5336    2021-11-19 19:33:10       1          movie            4
        1659    2021-11-19 19:35:39       0          sport            5
        6357    2021-11-19 19:37:02       0          movie            6
        7222    2021-11-19 19:38:50       0          movie           14
        1813    2021-11-19 19:40:26       1          sport            5
        1588    2021-11-19 19:40:42       0          sport           10
        4572    2021-11-19 19:41:53       0          movie            6
        1905    2021-11-19 19:43:50       1          sport            5
        2013    2021-11-19 19:45:57       0           tech           10
        4363    2021-11-19 19:47:57       0          movie           11
        4532    2021-11-19 19:50:56       0          movie            8
        2431    2021-11-19 19:53:34       0          covid            3
        6994    2021-11-19 19:54:58       0          movie            6
        180     2021-11-19 19:57:34       1       business            9
        2534    2021-11-19 19:57:51       0          covid            1
        7230    2021-11-19 19:59:08       0          movie           14
        5908    2021-11-19 20:01:15       0          movie           14
        4536    2021-11-19 20:02:36       1          movie           11
        7137    2021-11-19 20:03:27       0          movie            4
        2144    2021-11-19 20:05:06       0           tech           10
        194     2021-11-19 20:05:46       0       business           13
        2222    2021-11-19 20:06:12       0           tech            0
        473     2021-11-19 20:07:53       0       business           13
85411   1335    2021-12-03 10:10:28       0       politics            9
        778     2021-12-03 10:11:16       0  entertainment           10
        6298    2021-12-03 10:14:00       0          movie           11
        3959    2021-12-03 10:15:31       0          covid            7
        6088    2021-12-03 10:17:50       0          movie            8
        5827    2021-12-03 10:20:25       0          movie            8
        5521    2021-12-03 10:23:14       0          movie           14
        6054    2021-12-03 10:24:58       0          movie           11
        6757    2021-12-03 10:27:46       0          movie           11
        2142    2021-12-03 10:30:02       0           tech            0
        1360    2021-12-03 10:32:34       0       politics            9
        4151    2021-12-03 10:35:19       0          covid            7
        5491    2021-12-03 10:36:02       0          movie            2
        6267    2021-12-03 10:38:29       0          movie            4
        6974    2021-12-03 10:40:02       0          movie            4
        2860    2021-12-03 10:41:34       0          covid            7
        7092    2021-12-03 10:44:08       0          movie            8
        1472    2021-12-03 10:45:47       0          sport            5
        4219    2021-12-03 10:48:07       0          movie           14
        2241    2021-12-03 10:49:19       0           tech           10
        1746    2021-12-08 13:36:46       0          sport            5

                 DistanceTo1thCluster  DistanceTo2thCluster  \
user_id post_id
71774   1910                 0.508622              1.236053
        5971                 0.801371              1.183909
        679                  0.520916              1.218178
        3511                 1.217534              0.356532
        3320                 1.195418              0.479484
        1126                 0.573072              1.217702
        5336                 0.692750              1.109734
        1659                 0.577114              1.180136
        6357                 0.860176              0.980656
        7222                 0.966075              1.135989
        1813                 0.694065              1.145126
        1588                 0.672725              1.139963
        4572                 0.974535              0.830548
        1905                 0.497170              1.258643
        2013                 0.482925              1.146111
        4363                 1.119250              1.507522
        4532                 0.946925              1.370331
        2431                 1.077213              0.861275
        6994                 0.903682              0.860554
        180                  0.420271              1.224157
        2534                 1.223460              0.293173
        7230                 0.776845              1.171604
        5908                 1.101583              1.326861
        4536                 1.074890              1.398553
        7137                 0.752891              1.060917
        2144                 0.426090              1.138138
        194                  0.488732              1.188791
        2222                 0.269079              1.149550
        473                  0.587458              1.203253
85411   1335                 0.540352              1.228807
        778                  0.406155              1.199598
        6298                 1.044215              1.378775
        3959                 1.200180              0.352047
        6088                 0.844493              1.204596
        5827                 0.717803              1.242505
        5521                 0.789908              1.120285
        6054                 1.169806              1.313110
        6757                 0.960247              1.352208
        2142                 0.319822              1.262136
        1360                 0.523565              1.135671
        4151                 1.287848              0.526585
        5491                 0.685701              1.058969
        6267                 0.880646              1.299226
        6974                 0.770341              1.226051
        2860                 1.291920              0.454402
        7092                 0.822586              1.280399
        1472                 0.584912              1.129431
        4219                 1.006969              1.322605
        2241                 0.475575              1.165794
        1746                 0.951015              0.867482

                 DistanceTo3thCluster  DistanceTo4thCluster  \
user_id post_id
71774   1910                 0.763830              1.012481
        5971                 0.478061              0.838601
        679                  0.605768              1.092551
        3511                 1.173639              0.879275
        3320                 1.121344              0.803845
        1126                 0.716443              1.130900
        5336                 0.377544              0.849441
        1659                 0.696494              1.019763
        6357                 0.739419              1.342349
        7222                 0.505446              0.869633
        1813                 0.814995              0.930404
        1588                 0.678655              1.228547
        4572                 0.630346              0.989069
        1905                 0.706554              1.092224
        2013                 0.827714              1.279925
        4363                 0.890143              0.941437
        4532                 0.708790              0.959315
        2431                 1.036832              0.239030
        6994                 0.612174              1.145560
        180                  0.778386              1.202462
        2534                 1.198590              0.973150
        7230                 0.294442              0.930838
        5908                 0.700182              0.950226
        4536                 0.796914              0.839021
        7137                 0.478298              0.840269
        2144                 0.736848              1.225342
        194                  0.762204              1.179597
        2222                 0.669443              1.086294
        473                  0.744672              1.063536
85411   1335                 0.738650              1.084343
        778                  0.629077              1.183409
        6298                 0.698852              0.888185
        3959                 1.064497              0.758966
        6088                 0.495898              0.874732
        5827                 0.386482              1.002706
        5521                 0.346064              0.887550
        6054                 0.827806              0.860649
        6757                 0.704362              0.957494
        2142                 0.635166              1.003210
        1360                 0.770212              1.083760
        4151                 1.200912              0.854170
        5491                 0.336075              1.018497
        6267                 0.577222              0.882399
        6974                 0.483464              0.903859
        2860                 1.217085              0.787578
        7092                 0.592871              0.876539
        1472                 0.687996              1.038150
        4219                 0.629253              0.892199
        2241                 0.618817              1.250373
        1746                 0.902083              1.200129

                 DistanceTo5thCluster  DistanceTo6thCluster  ...  \
user_id post_id                                              ...
71774   1910                 0.764386              0.429453  ...
        5971                 0.322290              0.789486  ...
        679                  0.634221              0.531203  ...
        3511                 1.218847              1.159151  ...
        3320                 1.150067              1.119157  ...
        1126                 0.826211              0.538904  ...
        5336                 0.311127              0.680113  ...
        1659                 0.721875              0.444303  ...
        6357                 0.975011              0.859764  ...
        7222                 0.587638              0.910086  ...
        1813                 0.780360              0.420662  ...
        1588                 0.907311              0.502027  ...
        4572                 0.754132              0.900970  ...
        1905                 0.759664              0.389816  ...
        2013                 0.986806              0.714667  ...
        4363                 0.667019              1.116870  ...
        4532                 0.526459              0.909572  ...
        2431                 0.911988              1.047759  ...
        6994                 0.855191              0.820325  ...
        180                  0.866373              0.547249  ...
        2534                 1.251152              1.159501  ...
        7230                 0.360691              0.723453  ...
        5908                 0.686689              1.051218  ...
        4536                 0.536844              1.028949  ...
        7137                 0.428473              0.656021  ...
        2144                 0.884394              0.580270  ...
        194                  0.839911              0.479231  ...
        2222                 0.762423              0.646859  ...
        473                  0.772895              0.678948  ...
85411   1335                 0.780945              0.533932  ...
        778                  0.775301              0.591632  ...
        6298                 0.566958              1.012990  ...
        3959                 1.099102              1.046771  ...
        6088                 0.380632              0.801108  ...
        5827                 0.453955              0.781009  ...
        5521                 0.383673              0.727061  ...
        6054                 0.644224              1.124442  ...
        6757                 0.452194              0.867683  ...
        2142                 0.636575              0.613989  ...
        1360                 0.811632              0.585277  ...
        4151                 1.230129              1.192909  ...
        5491                 0.462656              0.634547  ...
        6267                 0.315017              0.845543  ...
        6974                 0.232393              0.776429  ...
        2860                 1.238228              1.212767  ...
        7092                 0.519366              0.841898  ...
        1472                 0.739288              0.232906  ...
        4219                 0.522244              0.978396  ...
        2241                 0.816141              0.628972  ...
        1746                 1.008237              0.650392  ...

                 DistanceTo15thCluster  gender  age  country       city  \
user_id post_id
71774   1910                  0.909735       0   20   Russia  Ulyanovsk
        5971                  0.369618       0   20   Russia  Ulyanovsk
        679                   0.770985       0   20   Russia  Ulyanovsk
        3511                  1.266399       0   20   Russia  Ulyanovsk
        3320                  1.199113       0   20   Russia  Ulyanovsk
        1126                  0.900778       0   20   Russia  Ulyanovsk
        5336                  0.404758       0   20   Russia  Ulyanovsk
        1659                  0.871688       0   20   Russia  Ulyanovsk
        6357                  1.038660       0   20   Russia  Ulyanovsk
        7222                  0.299083       0   20   Russia  Ulyanovsk
        1813                  0.894086       0   20   Russia  Ulyanovsk
        1588                  0.903559       0   20   Russia  Ulyanovsk
        4572                  0.675723       0   20   Russia  Ulyanovsk
        1905                  0.859289       0   20   Russia  Ulyanovsk
        2013                  1.068694       0   20   Russia  Ulyanovsk
        4363                  0.682390       0   20   Russia  Ulyanovsk
        4532                  0.654193       0   20   Russia  Ulyanovsk
        2431                  0.961007       0   20   Russia  Ulyanovsk
        6994                  0.836627       0   20   Russia  Ulyanovsk
        180                   0.999183       0   20   Russia  Ulyanovsk
        2534                  1.297434       0   20   Russia  Ulyanovsk
        7230                  0.267879       0   20   Russia  Ulyanovsk
        5908                  0.407754       0   20   Russia  Ulyanovsk
        4536                  0.549861       0   20   Russia  Ulyanovsk
        7137                  0.567468       0   20   Russia  Ulyanovsk
        2144                  1.010081       0   20   Russia  Ulyanovsk
        194                   0.971179       0   20   Russia  Ulyanovsk
        2222                  0.893594       0   20   Russia  Ulyanovsk
        473                   0.832500       0   20   Russia  Ulyanovsk
85411   1335                  0.898169       1   21   Russia    Irkutsk
        778                   0.909040       1   21   Russia    Irkutsk
        6298                  0.457713       1   21   Russia    Irkutsk
        3959                  1.108245       1   21   Russia    Irkutsk
        6088                  0.378648       1   21   Russia    Irkutsk
        5827                  0.445857       1   21   Russia    Irkutsk
        5521                  0.309629       1   21   Russia    Irkutsk
        6054                  0.596187       1   21   Russia    Irkutsk
        6757                  0.565489       1   21   Russia    Irkutsk
        2142                  0.751121       1   21   Russia    Irkutsk
        1360                  0.948415       1   21   Russia    Irkutsk
        4151                  1.272627       1   21   Russia    Irkutsk
        5491                  0.583723       1   21   Russia    Irkutsk
        6267                  0.451944       1   21   Russia    Irkutsk
        6974                  0.468951       1   21   Russia    Irkutsk
        2860                  1.236655       1   21   Russia    Irkutsk
        7092                  0.513848       1   21   Russia    Irkutsk
        1472                  0.845408       1   21   Russia    Irkutsk
        4219                  0.375792       1   21   Russia    Irkutsk
        2241                  0.910372       1   21   Russia    Irkutsk
        1746                  1.098075       1   21   Russia    Irkutsk

                 exp_group   os  source  hour  month
user_id post_id
71774   1910             4  iOS     ads    23     11
        5971             4  iOS     ads    23     11
        679              4  iOS     ads    23     11
        3511             4  iOS     ads    23     11
        3320             4  iOS     ads    23     11
        1126             4  iOS     ads    19     11
        5336             4  iOS     ads    19     11
        1659             4  iOS     ads    19     11
        6357             4  iOS     ads    19     11
        7222             4  iOS     ads    19     11
        1813             4  iOS     ads    19     11
        1588             4  iOS     ads    19     11
        4572             4  iOS     ads    19     11
        1905             4  iOS     ads    19     11
        2013             4  iOS     ads    19     11
        4363             4  iOS     ads    19     11
        4532             4  iOS     ads    19     11
        2431             4  iOS     ads    19     11
        6994             4  iOS     ads    19     11
        180              4  iOS     ads    19     11
        2534             4  iOS     ads    19     11
        7230             4  iOS     ads    19     11
        5908             4  iOS     ads    20     11
        4536             4  iOS     ads    20     11
        7137             4  iOS     ads    20     11
        2144             4  iOS     ads    20     11
        194              4  iOS     ads    20     11
        2222             4  iOS     ads    20     11
        473              4  iOS     ads    20     11
85411   1335             2  iOS     ads    10     12
        778              2  iOS     ads    10     12
        6298             2  iOS     ads    10     12
        3959             2  iOS     ads    10     12
        6088             2  iOS     ads    10     12
        5827             2  iOS     ads    10     12
        5521             2  iOS     ads    10     12
        6054             2  iOS     ads    10     12
        6757             2  iOS     ads    10     12
        2142             2  iOS     ads    10     12
        1360             2  iOS     ads    10     12
        4151             2  iOS     ads    10     12
        5491             2  iOS     ads    10     12
        6267             2  iOS     ads    10     12
        6974             2  iOS     ads    10     12
        2860             2  iOS     ads    10     12
        7092             2  iOS     ads    10     12
        1472             2  iOS     ads    10     12
        4219             2  iOS     ads    10     12
        2241             2  iOS     ads    10     12
        1746             2  iOS     ads    13     12

[50 rows x 28 columns]

### Пора обучать модели!

In [21]:
### Как валидировать? Как разобьем на train и test?
### Предлагаю по времени, так как данные имеют 
### Временную структуру! Хотим корректно оценивать
### Вероятности для будущих рекомендаций

max(df.timestamp), min(df.timestamp)

(Timestamp('2021-12-29 23:43:31'), Timestamp('2021-10-01 06:01:40'))

In [22]:
### За отсечку возьмем 2021-12-15

df_train = df[df.timestamp < '2021-12-15']
df_test = df[df.timestamp >= '2021-12-15']

df_train = df_train.drop('timestamp', axis=1)
df_test = df_test.drop('timestamp', axis=1)

X_train = df_train.drop('target', axis=1)
X_test = df_test.drop('target', axis=1)

y_train = df_train['target']
y_test = df_test['target']

y_train.shape, y_test.shape

((7469550,), (1463065,))

In [23]:
X_train

                         topic  TextCluster  DistanceTo1thCluster  \
user_id post_id
71774   1910             sport            5              0.508622
        5971             movie            4              0.801371
        679      entertainment           12              0.520916
        3511             covid            7              1.217534
        3320             covid            7              1.195418
...                        ...          ...                   ...
34726   5387             movie            4              0.888198
        3134             covid            7              1.136676
        4504             movie           14              0.951441
87565   3083             covid            7              1.348620
        5942             movie           14              0.929165

                 DistanceTo2thCluster  DistanceTo3thCluster  \
user_id post_id
71774   1910                 1.236053              0.763830
        5971                 1.183909              0.478061
        679                  1.218178              0.605768
        3511                 0.356532              1.173639
        3320                 0.479484              1.121344
...                               ...                   ...
34726   5387                 1.356165              0.658933
        3134                 0.512370              1.104000
        4504                 1.247900              0.589883
87565   3083                 0.427205              1.203795
        5942                 1.328479              0.623917

                 DistanceTo4thCluster  DistanceTo5thCluster  \
user_id post_id
71774   1910                 1.012481              0.764386
        5971                 0.838601              0.322290
        679                  1.092551              0.634221
        3511                 0.879275              1.218847
        3320                 0.803845              1.150067
...                               ...                   ...
34726   5387                 0.933910              0.402354
        3134                 0.881572              1.148420
        4504                 0.889483              0.517137
87565   3083                 0.838663              1.240797
        5942                 0.885815              0.547973

                 DistanceTo6thCluster  DistanceTo7thCluster  \
user_id post_id
71774   1910                 0.429453              1.056280
        5971                 0.789486              0.883998
        679                  0.531203              0.920499
        3511                 1.159151              0.872360
        3320                 1.119157              0.913641
...                               ...                   ...
34726   5387                 0.899975              1.097564
        3134                 1.066591              0.855563
        4504                 0.952579              0.947010
87565   3083                 1.224323              0.905643
        5942                 0.911706              1.095916

                 DistanceTo8thCluster  ...  DistanceTo15thCluster  gender  \
user_id post_id                        ...
71774   1910                 1.176828  ...               0.909735       0
        5971                 1.158633  ...               0.369618       0
        679                  1.203230  ...               0.770985       0
        3511                 0.238470  ...               1.266399       0
        3320                 0.249585  ...               1.199113       0
...                               ...  ...                    ...     ...
34726   5387                 1.312049  ...               0.581763       1
        3134                 0.282249  ...               1.213962       1
        4504                 1.244146  ...               0.324598       1
87565   3083                 0.420803  ...               1.209620       1
        5942                 1.306024  ...               0.358157       1

                 age  country       city  exp_group       os  source  hour  \
user_id post_id
71774   1910      20   Russia  Ulyanovsk          4      iOS     ads    23
        5971      20   Russia  Ulyanovsk          4      iOS     ads    23
        679       20   Russia  Ulyanovsk          4      iOS     ads    23
        3511      20   Russia  Ulyanovsk          4      iOS     ads    23
        3320      20   Russia  Ulyanovsk          4      iOS     ads    23
...              ...      ...        ...        ...      ...     ...   ...
34726   5387      41   Russia      Tomsk          1  Android     ads    18
        3134      41   Russia      Tomsk          1  Android     ads    18
        4504      41   Russia      Tomsk          1  Android     ads    18
87565   3083      19   Russia    Vologda          0  Android     ads    19
        5942      19   Russia    Vologda          0  Android     ads    19

                month
user_id post_id
71774   1910       11
        5971       11
        679        11
        3511       11
        3320       11
...               ...
34726   5387       12
        3134       12
        4504       12
87565   3083       10
        5942       10

[7469550 rows x 26 columns]

In [24]:
### Обучим катбуст!

from catboost import CatBoostClassifier


catboost = CatBoostClassifier(
    iterations=200,
    learning_rate=1,
    depth=2
)

object_cols = [
    'topic', 'TextCluster', 'gender', 'country',
    'city', 'exp_group', 'hour', 'month',
    'os', 'source'
]

catboost.fit(X_train, y_train, object_cols)

0:	learn: 0.3559618	total: 917ms	remaining: 3m 2s
1:	learn: 0.3488913	total: 1.57s	remaining: 2m 36s
2:	learn: 0.3473165	total: 2.41s	remaining: 2m 38s
3:	learn: 0.3464610	total: 3.05s	remaining: 2m 29s
4:	learn: 0.3459340	total: 3.73s	remaining: 2m 25s
5:	learn: 0.3457275	total: 4.32s	remaining: 2m 19s
6:	learn: 0.3456062	total: 4.89s	remaining: 2m 14s
7:	learn: 0.3447692	total: 5.5s	remaining: 2m 11s
8:	learn: 0.3446067	total: 6.1s	remaining: 2m 9s
9:	learn: 0.3443868	total: 6.55s	remaining: 2m 4s
10:	learn: 0.3440904	total: 7.05s	remaining: 2m 1s
11:	learn: 0.3439649	total: 7.69s	remaining: 2m
12:	learn: 0.3438050	total: 8.21s	remaining: 1m 58s
13:	learn: 0.3436483	total: 8.68s	remaining: 1m 55s
14:	learn: 0.3435677	total: 9.16s	remaining: 1m 52s
15:	learn: 0.3434843	total: 9.71s	remaining: 1m 51s
16:	learn: 0.3432768	total: 10.3s	remaining: 1m 50s
17:	learn: 0.3432412	total: 10.8s	remaining: 1m 49s
18:	learn: 0.3432068	total: 11.3s	remaining: 1m 47s
19:	learn: 0.3431923	total: 11.8s	remaining: 1m 46s
20:	learn: 0.3426268	total: 12.5s	remaining: 1m 46s
21:	learn: 0.3425940	total: 13.1s	remaining: 1m 45s
22:	learn: 0.3421610	total: 13.8s	remaining: 1m 46s
23:	learn: 0.3414887	total: 14.4s	remaining: 1m 45s
24:	learn: 0.3413165	total: 15s	remaining: 1m 45s
25:	learn: 0.3412640	total: 15.7s	remaining: 1m 44s
26:	learn: 0.3411764	total: 16.3s	remaining: 1m 44s
27:	learn: 0.3411483	total: 16.9s	remaining: 1m 43s
28:	learn: 0.3409986	total: 17.5s	remaining: 1m 43s
29:	learn: 0.3407645	total: 18.1s	remaining: 1m 42s
30:	learn: 0.3407423	total: 18.7s	remaining: 1m 41s
31:	learn: 0.3407162	total: 19.3s	remaining: 1m 41s
32:	learn: 0.3406849	total: 19.9s	remaining: 1m 40s
33:	learn: 0.3406670	total: 20.5s	remaining: 1m 40s
34:	learn: 0.3405967	total: 21.2s	remaining: 1m 39s
35:	learn: 0.3405391	total: 21.8s	remaining: 1m 39s
36:	learn: 0.3404865	total: 22.4s	remaining: 1m 38s
37:	learn: 0.3404717	total: 23.1s	remaining: 1m 38s
38:	learn: 0.3404325	total: 23.7s	remaining: 1m 37s
39:	learn: 0.3404084	total: 24.3s	remaining: 1m 37s
40:	learn: 0.3403334	total: 25s	remaining: 1m 36s
41:	learn: 0.3402961	total: 25.6s	remaining: 1m 36s
42:	learn: 0.3402659	total: 26.1s	remaining: 1m 35s
43:	learn: 0.3402337	total: 26.7s	remaining: 1m 34s
44:	learn: 0.3402148	total: 27.3s	remaining: 1m 33s
45:	learn: 0.3401904	total: 27.8s	remaining: 1m 33s
46:	learn: 0.3401779	total: 28.3s	remaining: 1m 32s
47:	learn: 0.3401710	total: 29s	remaining: 1m 31s
48:	learn: 0.3401598	total: 29.6s	remaining: 1m 31s
49:	learn: 0.3401482	total: 30.2s	remaining: 1m 30s
50:	learn: 0.3401208	total: 30.8s	remaining: 1m 30s
51:	learn: 0.3400884	total: 31.4s	remaining: 1m 29s
52:	learn: 0.3400638	total: 32s	remaining: 1m 28s
53:	learn: 0.3400572	total: 32.6s	remaining: 1m 28s
54:	learn: 0.3400449	total: 33.2s	remaining: 1m 27s
55:	learn: 0.3400126	total: 33.8s	remaining: 1m 26s
56:	learn: 0.3400012	total: 34.4s	remaining: 1m 26s
57:	learn: 0.3399860	total: 35s	remaining: 1m 25s
58:	learn: 0.3397551	total: 35.6s	remaining: 1m 25s
59:	learn: 0.3397482	total: 36.2s	remaining: 1m 24s
60:	learn: 0.3397431	total: 36.9s	remaining: 1m 23s
61:	learn: 0.3397259	total: 37.5s	remaining: 1m 23s
62:	learn: 0.3397180	total: 38.2s	remaining: 1m 23s
63:	learn: 0.3396971	total: 38.8s	remaining: 1m 22s
64:	learn: 0.3396888	total: 39.4s	remaining: 1m 21s
65:	learn: 0.3396808	total: 40s	remaining: 1m 21s
66:	learn: 0.3396655	total: 40.6s	remaining: 1m 20s
67:	learn: 0.3396545	total: 41.2s	remaining: 1m 20s
68:	learn: 0.3396166	total: 41.8s	remaining: 1m 19s
69:	learn: 0.3395540	total: 42.4s	remaining: 1m 18s
70:	learn: 0.3395400	total: 43s	remaining: 1m 18s
71:	learn: 0.3395247	total: 43.6s	remaining: 1m 17s
72:	learn: 0.3395183	total: 44.2s	remaining: 1m 16s
73:	learn: 0.3395088	total: 44.8s	remaining: 1m 16s
74:	learn: 0.3394917	total: 45.4s	remaining: 1m 15s
75:	learn: 0.3394712	total: 46s	remaining: 1m 15s
76:	learn: 0.3394670	total: 46.5s	remaining: 1m 14s
77:	learn: 0.3394575	total: 47.1s	remaining: 1m 13s
78:	learn: 0.3394186	total: 47.7s	remaining: 1m 13s
79:	learn: 0.3393945	total: 48.4s	remaining: 1m 12s
80:	learn: 0.3393722	total: 49s	remaining: 1m 12s
81:	learn: 0.3393643	total: 49.7s	remaining: 1m 11s
82:	learn: 0.3393437	total: 50.3s	remaining: 1m 10s
83:	learn: 0.3393372	total: 50.9s	remaining: 1m 10s
84:	learn: 0.3393284	total: 51.6s	remaining: 1m 9s
85:	learn: 0.3393222	total: 52.1s	remaining: 1m 9s
86:	learn: 0.3392951	total: 52.8s	remaining: 1m 8s
87:	learn: 0.3392852	total: 53.4s	remaining: 1m 7s
88:	learn: 0.3392727	total: 54s	remaining: 1m 7s
89:	learn: 0.3392570	total: 54.5s	remaining: 1m 6s
90:	learn: 0.3392324	total: 55.1s	remaining: 1m 6s
91:	learn: 0.3392266	total: 55.7s	remaining: 1m 5s
92:	learn: 0.3392090	total: 56.3s	remaining: 1m 4s
93:	learn: 0.3392002	total: 56.9s	remaining: 1m 4s
94:	learn: 0.3391494	total: 57.5s	remaining: 1m 3s
95:	learn: 0.3391083	total: 58.2s	remaining: 1m 3s
96:	learn: 0.3390588	total: 58.8s	remaining: 1m 2s
97:	learn: 0.3390260	total: 59.4s	remaining: 1m 1s
98:	learn: 0.3390131	total: 1m	remaining: 1m 1s
99:	learn: 0.3390025	total: 1m	remaining: 1m
100:	learn: 0.3389974	total: 1m 1s	remaining: 1m
101:	learn: 0.3389922	total: 1m 1s	remaining: 59.5s
102:	learn: 0.3389651	total: 1m 2s	remaining: 58.9s
103:	learn: 0.3389586	total: 1m 3s	remaining: 58.2s
104:	learn: 0.3389368	total: 1m 3s	remaining: 57.6s
105:	learn: 0.3389230	total: 1m 4s	remaining: 57s
106:	learn: 0.3389099	total: 1m 4s	remaining: 56.4s
107:	learn: 0.3388831	total: 1m 5s	remaining: 55.7s
108:	learn: 0.3388757	total: 1m 6s	remaining: 55.1s
109:	learn: 0.3388687	total: 1m 6s	remaining: 54.5s
110:	learn: 0.3388636	total: 1m 7s	remaining: 53.9s
111:	learn: 0.3388465	total: 1m 7s	remaining: 53.3s
112:	learn: 0.3388252	total: 1m 8s	remaining: 52.7s
113:	learn: 0.3388225	total: 1m 9s	remaining: 52.1s
114:	learn: 0.3388148	total: 1m 9s	remaining: 51.5s
115:	learn: 0.3388055	total: 1m 10s	remaining: 50.9s
116:	learn: 0.3387893	total: 1m 10s	remaining: 50.3s
117:	learn: 0.3387810	total: 1m 11s	remaining: 49.7s
118:	learn: 0.3387449	total: 1m 12s	remaining: 49.1s
119:	learn: 0.3387255	total: 1m 12s	remaining: 48.5s
120:	learn: 0.3387134	total: 1m 13s	remaining: 47.9s
121:	learn: 0.3387077	total: 1m 13s	remaining: 47.3s
122:	learn: 0.3387012	total: 1m 14s	remaining: 46.7s
123:	learn: 0.3386976	total: 1m 15s	remaining: 46s
124:	learn: 0.3386897	total: 1m 15s	remaining: 45.4s
125:	learn: 0.3386841	total: 1m 16s	remaining: 44.8s
126:	learn: 0.3386783	total: 1m 16s	remaining: 44.2s
127:	learn: 0.3386752	total: 1m 17s	remaining: 43.6s
128:	learn: 0.3386637	total: 1m 18s	remaining: 43.1s
129:	learn: 0.3386473	total: 1m 18s	remaining: 42.5s
130:	learn: 0.3386443	total: 1m 19s	remaining: 41.9s
131:	learn: 0.3386259	total: 1m 20s	remaining: 41.3s
132:	learn: 0.3386164	total: 1m 20s	remaining: 40.6s
133:	learn: 0.3386086	total: 1m 21s	remaining: 40s
134:	learn: 0.3385976	total: 1m 21s	remaining: 39.4s
135:	learn: 0.3385906	total: 1m 22s	remaining: 38.8s
136:	learn: 0.3385587	total: 1m 22s	remaining: 38.2s
137:	learn: 0.3385468	total: 1m 23s	remaining: 37.6s
138:	learn: 0.3385400	total: 1m 24s	remaining: 37s
139:	learn: 0.3385308	total: 1m 24s	remaining: 36.4s
140:	learn: 0.3385214	total: 1m 25s	remaining: 35.8s
141:	learn: 0.3385138	total: 1m 26s	remaining: 35.2s
142:	learn: 0.3385039	total: 1m 26s	remaining: 34.6s
143:	learn: 0.3384988	total: 1m 27s	remaining: 34s
144:	learn: 0.3384943	total: 1m 28s	remaining: 33.4s
145:	learn: 0.3384884	total: 1m 28s	remaining: 32.8s
146:	learn: 0.3384871	total: 1m 29s	remaining: 32.2s
147:	learn: 0.3384758	total: 1m 29s	remaining: 31.6s
148:	learn: 0.3384654	total: 1m 30s	remaining: 31s
149:	learn: 0.3384562	total: 1m 31s	remaining: 30.4s
150:	learn: 0.3384294	total: 1m 31s	remaining: 29.7s
151:	learn: 0.3384214	total: 1m 32s	remaining: 29.1s
152:	learn: 0.3384169	total: 1m 32s	remaining: 28.5s
153:	learn: 0.3384073	total: 1m 33s	remaining: 27.9s
154:	learn: 0.3383982	total: 1m 34s	remaining: 27.3s
155:	learn: 0.3383903	total: 1m 34s	remaining: 26.8s
156:	learn: 0.3383835	total: 1m 35s	remaining: 26.1s
157:	learn: 0.3383745	total: 1m 36s	remaining: 25.5s
158:	learn: 0.3383643	total: 1m 36s	remaining: 24.9s

159:	learn: 0.3383600	total: 1m 37s	remaining: 24.3s
160:	learn: 0.3383568	total: 1m 37s	remaining: 23.7s
161:	learn: 0.3383531	total: 1m 38s	remaining: 23.1s
162:	learn: 0.3383467	total: 1m 39s	remaining: 22.5s
163:	learn: 0.3383411	total: 1m 39s	remaining: 21.9s
164:	learn: 0.3383331	total: 1m 40s	remaining: 21.3s
165:	learn: 0.3383274	total: 1m 40s	remaining: 20.7s
166:	learn: 0.3383212	total: 1m 41s	remaining: 20.1s
167:	learn: 0.3383143	total: 1m 42s	remaining: 19.4s
168:	learn: 0.3383087	total: 1m 42s	remaining: 18.8s
169:	learn: 0.3382926	total: 1m 43s	remaining: 18.2s
170:	learn: 0.3382897	total: 1m 43s	remaining: 17.6s
171:	learn: 0.3382882	total: 1m 44s	remaining: 17s
172:	learn: 0.3382835	total: 1m 45s	remaining: 16.4s
173:	learn: 0.3382752	total: 1m 45s	remaining: 15.8s
174:	learn: 0.3382720	total: 1m 46s	remaining: 15.2s
175:	learn: 0.3382554	total: 1m 46s	remaining: 14.6s
176:	learn: 0.3382498	total: 1m 47s	remaining: 14s
177:	learn: 0.3382445	total: 1m 48s	remaining: 13.4s
178:	learn: 0.3382407	total: 1m 48s	remaining: 12.8s
179:	learn: 0.3382344	total: 1m 49s	remaining: 12.2s
180:	learn: 0.3382032	total: 1m 49s	remaining: 11.5s
181:	learn: 0.3381911	total: 1m 50s	remaining: 10.9s
182:	learn: 0.3381843	total: 1m 51s	remaining: 10.3s
183:	learn: 0.3381771	total: 1m 51s	remaining: 9.73s
184:	learn: 0.3381513	total: 1m 52s	remaining: 9.12s
185:	learn: 0.3381347	total: 1m 53s	remaining: 8.52s
186:	learn: 0.3381253	total: 1m 53s	remaining: 7.91s
187:	learn: 0.3381235	total: 1m 54s	remaining: 7.3s
188:	learn: 0.3381226	total: 1m 54s	remaining: 6.69s
189:	learn: 0.3381110	total: 1m 55s	remaining: 6.08s
190:	learn: 0.3381029	total: 1m 56s	remaining: 5.47s
191:	learn: 0.3380863	total: 1m 56s	remaining: 4.86s
192:	learn: 0.3380841	total: 1m 57s	remaining: 4.26s
193:	learn: 0.3380786	total: 1m 57s	remaining: 3.65s
194:	learn: 0.3380670	total: 1m 58s	remaining: 3.04s
195:	learn: 0.3380596	total: 1m 59s	remaining: 2.43s
196:	learn: 0.3380541	total: 1m 59s	remaining: 1.82s
197:	learn: 0.3380473	total: 2m	remaining: 1.22s
198:	learn: 0.3380384	total: 2m	remaining: 608ms
199:	learn: 0.3380134	total: 2m 1s	remaining: 0us

In [25]:
### Замерим качество работы такой модели
### Возьмем ROC-AUC
from sklearn.metrics import roc_auc_score


print(f"Качество на трейне: {roc_auc_score(y_train, catboost.predict_proba(X_train)[:, 1])}")
print(f"Качество на тесте: {roc_auc_score(y_test, catboost.predict_proba(X_test)[:, 1])}")

Качество на трейне: 0.6822534443400146
Качество на тесте: 0.6551606754082114

In [26]:
### Сохраним модель

catboost.save_model(
    'catboost_model',
    format="cbm"                  
)

### Положим в базу фичи, необходимые для функционала нашей модели

In [27]:
posts_info.to_sql(
   "posts_info_features_dl",                    
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml",                      
    schema="public",               
    if_exists='replace'            
   )

23

In [28]:
### Все ли норм?

test_ = pd.read_sql(
    """SELECT * FROM public.posts_info_features_dl""",
    
    con="postgresql://robot-startml-ro:pheiph0hahj1Vaif@"
        "postgres.lab.karpov.courses:6432/startml"
)

test_

,index,post_id,text,topic,TextCluster,DistanceTo1thCluster,DistanceTo2thCluster,DistanceTo3thCluster,DistanceTo4thCluster,DistanceTo5thCluster,DistanceTo6thCluster,DistanceTo7thCluster,DistanceTo8thCluster,DistanceTo9thCluster,DistanceTo10thCluster,DistanceTo11thCluster,DistanceTo12thCluster,DistanceTo13thCluster,DistanceTo14thCluster,DistanceTo15thCluster
0,0,1,UK economy facing major risks\n\nThe UK manufa...,business,13,0.678915,1.242555,0.925453,1.328623,1.035016,0.746756,1.047396,1.202398,1.058816,0.596554,0.467959,1.303139,0.779649,0.433943,1.151153
1,1,2,Aids and climate top Davos agenda\n\nClimate c...,business,10,0.515767,1.086312,0.754733,1.208146,0.895864,0.575891,0.841598,1.078090,0.892187,0.450967,0.243006,1.176879,0.563903,0.364549,1.013353
2,2,3,Asian quake hits European shares\n\nShares in ...,business,13,0.553639,1.224138,0.759190,1.176707,0.880581,0.614857,1.001670,1.190090,0.842709,0.628899,0.521435,1.099705,0.623288,0.311780,0.961329
3,3,4,India power shares jump on debut\n\nShares in ...,business,13,0.641349,1.051243,0.782907,1.173028,0.909068,0.704925,0.837270,1.043599,0.931570,0.706521,0.426988,1.166589,0.677383,0.349437,0.995106
4,4,5,Lacroix label bought by US firm\n\nLuxury good...,business,13,0.528634,1.014662,0.661138,0.983044,0.709366,0.548295,0.810834,0.984994,0.748542,0.590418,0.442702,0.955124,0.436692,0.322252,0.830842
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7018,7018,7315,"OK, I would not normally watch a Farrelly brot...",movie,2,0.748239,1.124338,0.288776,1.002764,0.455884,0.657267,0.766429,1.118941,0.501734,0.768604,0.739578,0.706079,0.570278,0.746623,0.431315
7019,7019,7316,I give this movie 2 stars purely because of it...,movie,14,0.928993,1.299645,0.567184,0.921160,0.470867,0.929882,0.978501,1.292749,0.498946,1.025573,1.116908,0.338542,0.809883,0.991397,0.279870
7020,7020,7317,I cant believe this film was allowed to be mad...,movie,14,0.907572,1.086253,0.479368,0.824388,0.518709,0.864067,0.829638,1.089858,0.531335,0.968415,1.008427,0.521602,0.764485,0.944763,0.289178
7021,7021,7318,The version I saw of this film was the Blockbu...,movie,11,0.843836,1.355964,0.567953,0.922451,0.344325,0.866135,1.080506,1.325952,0.366608,0.942277,1.066244,0.300012,0.701426,0.920168,0.425252
7022,7022,7319,Piece of subtle art. Maybe a masterpiece. Doub...,movie,8,0.827589,1.178095,0.636255,0.894092,0.524678,0.801488,0.904940,1.172298,0.485548,0.887864,0.971375,0.611855,0.749999,0.910859,0.667655